### ISSUE TITLE
Timestampable sets 0000-00-00 00:00:00 datetime

### ISSUE THREAD

**Issue by thomas2411** [Atlantic18/DoctrineExtensions#1035]
Timestampable sets 0000-00-00 00:00:00 datetime so I have error: This year is invalid. Somehow it wants to set date like this:

```
at PropertyPathMapper ->mapDataToForms (array('date' => array('year' => '-1', 'month' => '11', 'day' => '30'), 'time' => array('hour' => '0', 'minute' => '0')), object(RecursiveIteratorIterator))
in /Users/user/WWW/project/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 385 
```

My configuration is:

``` yml
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true    
            sortable: true
```

In my Entity:

``` yml
MyBundle\Entity\Screen:
    type:  entity
    table: screen
    repositoryClass: ScreenRepository
    id:
        id:
            type: integer
            unique: true
            generator:
                strategy: AUTO
    fields:
        nazwa:
            type: string
            length: 256
        opublikowany:
            type: boolean
            nullable: true
        kolejnosc:
          type: integer
          gedmo:
            - sortablePosition
        created:
          type: datetime
          gedmo:
            timestampable:
              on: create
        updated:
          type: datetime
          gedmo:
            timestampable:
              on: update    
    manyToOne:
        createdBy:
          targetEntity: User
          joinColumn:
              name: created_by
              referencedColumnName: id
              nullable: true   
          gedmo:
            blameable:
              on: create   
        updatedBy:
          targetEntity: User
          joinColumn:
              name: updated_by
              referencedColumnName: id
              nullable: true   
          gedmo:
            blameable:
              on: update   
```

Why this is happening? Why it wants to set date as zeros? I have set default Timezone in PHP, I use utf8_general_ci in MySQL database. What's going on?
