### ISSUE TITLE
ReferencesListener not calling preUpdate

### ISSUE THREAD

**Issue by webdevilopers** [Atlantic18/DoctrineExtensions#1152]
Since there still seems to be an issue with the `orm` and `odm` config for the `ReferencesListener` - see https://github.com/Atlantic18/DoctrineExtensions/issues/821 - I only have configured the `odm` this way:
```yaml
services:
#    gedmo.listener.reference.mysql:
#        class: Gedmo\References\ReferencesListener
#        tags:
##            - { name: doctrine.event_subscriber, connection: game }
#            - { name: doctrine.event_subscriber }
#        calls:
#            - [ setAnnotationReader, [ "@annotation_reader" ] ]
#            - [ registerManager, [ 'document', "@doctrine_mongodb.odm.document_manager" ] ]

    gedmo.listener.reference.mongodb:
         class: Gedmo\References\ReferencesListener
         tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
         calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ registerManager, [ 'entity', "@doctrine.orm.entity_manager" ] ]    
```

My `Payroll` Document is linkend to a `Branch` Entity:
```php
/**
 * @MongoDB\Document
 */
class Payroll
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @Gedmo\ReferenceOne(type="entity", class="Plusquam\Bundle\ContractBundle\Entity\Branch", identifier="branch_id")
     */
    protected $branch;

    /**
     * @MongoDB\Int
     */
    protected $branch_id;

    public function setBranch(Branch $branch)
    {
        $this->branch = $branch;
    }

    public function getBranch()
    {
        return $this->branch;
    }

    public function setBranchId($branchId)
    {
        $this->branch_id = $branchId;
//        $this->branchId = $branchId;
    }

    public function getBranchId()
    {
//        return $this->branchId;
        return $this->branch_id;
    }
```

I can successfully create a new Document with the Entity relation. But I can't update it:
```php
        $em = $this->getDoctrine()->getEntityManager();

        $branch = $em->getReference('Plusquam\Bundle\ContractBundle\Entity\Branch', 2);

        $payroll = new \Plusquam\Bundle\TimekeepingBundle\Document\Payroll();
        $payroll->setBranch($branch);

        $dm = $this->get('doctrine_mongodb')->getManager();
        $dm->persist($payroll);
        $dm->flush();

        var_dump($payroll);

        $branch = $em->getReference('Plusquam\Bundle\ContractBundle\Entity\Branch', 4);
        $payroll->setBranch($branch);
        $dm->persist($payroll);
        $dm->flush();

        var_dump($payroll);

        $dm->find('Plusquam\Bundle\TimekeepingBundle\Document\Payroll', $payroll->getId());
        $branch = $em->getReference('Plusquam\Bundle\ContractBundle\Entity\Branch', 6);
        $payroll->setBranch($branch);
        $dm->persist($payroll);
        $dm->flush();

        var_dump($payroll);
```

I added some output to the ReferencesListener methods:
```php
    public function prePersist(EventArgs $eventArgs)
    {echo "CREATE";
        $this->updateReferences($eventArgs);
    }

    public function preUpdate(EventArgs $eventArgs)
    {echo "UPDATE";
        $this->updateReferences($eventArgs);
    }
```

The `prePersist` is called but never the `preUpdate`.

Is a different service config required to make it work for updating?
