### ISSUE TITLE
[Timestampable] Fields remain null when using entity managers detach and merge methods

### ISSUE THREAD

**Issue by phillipsnick** [Atlantic18/DoctrineExtensions#1255]
I had a feeling that I have missing some configuration somewhere which is causing this issue, but after spending 2 hours debugging getting no where I'm starting to wonder if it's a bug or expected behaviour.

To keep this example as simplified as possible, I'm creating an `Address` entity, detaching from the entity manager then merging it back into the entity manager. In the actual app I'm detaching, storing it in the session, then merging it back into the entity manager a few requests later to save it (attempt to reduce DB writes due to low conversion rate). But doing so results in Doctrine trying to write null values to createdAt and updatedAt.

Here are two examples

__Working example__

```php
$address = new Address();
$address
    ->setLine1('Line 1')
    ->setCity('City')
    ->setPostcode('AB1 2CD');

$em->persist($address);
$em->flush();
```

SQL Executed on DB:

```sql
INSERT INTO addresses (line1, city, postcode, createdAt, updatedAt) VALUES ('Line 1', 'City', 'AB1 2CD', '2015-02-25 14:54:23', '2015-02-25 14:54:23')
```

__Failure when detaching and merging__

```php
$address = new Address();
$address
    ->setLine1('Line 1')
    ->setCity('City')
    ->setPostcode('AB1 2CD');

$em->detach($address);

$newAddress = $em->merge($address);
$em->persist($newAddress);
$em->flush();
```

Resulting SQL:

```sql
INSERT INTO addresses (line1, city, postcode, createdAt, updatedAt) VALUES ('Line 1', 'City', 'AB1 2CD', NULL, NULL)
```

__Entity config__

```yml
Namespace\Entity\Address:
  type: entity
  table: addresses
  id:
    addressId:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: AUTO
  fields:
    line1:
      type: string
      length: 45
    city:
      type: string
      length: 45
    postcode:
      type: string
      length: 45
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
```

Doctrine extensions config (Symfony2)

```yml
stof_doctrine_extensions:
  orm:
    default:
      timestampable: true
      softdeleteable: true
      sluggable: true
```

Anyway I have dug into the code and believe it's to do with this line as it's not had it's property changed:
https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Timestampable/TimestampableListener.php#L187
