### ISSUE TITLE
Issue with Translate

### ISSUE THREAD

**Issue by nicoip** [Atlantic18/DoctrineExtensions#1374]
Hi everybody,

I have an issue with A2lx when its pluged with Generator Bundle.

I'm using Symfony 2.7.1.

I searched the solution long time and i didn't find an answer.

The A2lix's repository has nothing on it and it seems it take long time to have an answer to...

So i come to you, and hope that someone have a solution to well configure this two bundle to work together.

Her is the config.yml :

```
# A2lix
a2lix_translation_form:
    locale_provider: default       
    locales: [en, fr]          
    default_locale: %locale%             
    required_locales: [fr]
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
       
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"                
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    translatable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translatable\Entity
                        # make sure vendor library location is correct
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"               

#AdminGenerator
admingenerator_generator:
    generator_cache: global_cache.provider
    # choose  and enable at least one
    use_propel:          false
    use_doctrine_orm:    true
    use_doctrine_odm:    false
    overwrite_if_exists: false
    base_admin_template: AdmingeneratorGeneratorBundle::base_uncompressed.html.twig
    #dashboard_welcome_path: root vers le dashboard de l'admin
    #dashboard_route:     MyDashboard_path
    generator_cache: global_cache.provider
    login_route: fos_user_security_login
    logout_route: fos_user_security_logout
    twig:
        use_form_resources: true
        use_localized_date: false
        date_format: Y-m-d
        datetime_format: Y-m-d H:i:s
        localized_date_format: medium
        localized_datetime_format: medium
        number_format:
            decimal: 0
            decimal_point: .
            thousand_separator: ,
    templates_dirs: []
    stylesheets: []
    javascripts: []
```
Here is the  entity Admin.php (there is the field 'fonction' i want to translate) :

```
namespace Ip\AdminBundle\Entity;

use PUGX\MultiUserBundle\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Translatable\Translatable;
use Ip\UserBundle\Entity\User as User;

/**
 * Admin
 *
 * @ORM\Table(name="admin")
 * @ORM\Entity(repositoryClass="Ip\AdminBundle\Entity\AdminRepository")
 * @UniqueEntity(fields = "username", targetClass = "Ip\UserBundle\Entity\User", message="fos_user.username.already_used")
 * @UniqueEntity(fields = "email", targetClass = "Ip\UserBundle\Entity\User", message="fos_user.email.already_used")
 * @Gedmo\TranslationEntity(class="Ip\AdminBundle\Entity\AdminTranslation")
 */
class Admin extends User implements Translatable 
{    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
        
    /**
     * @Gedmo\Locale
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     */
    protected $locale;
    
    /**
     * @var string
     * @Gedmo\Translatable
     * @ORM\Column(name="fonction", type="string", length=50, nullable=true)
     */
    private $fonction;  
    
    /**
     * @ORM\OneToMany(
     *     targetEntity="Ip\AdminBundle\Entity\AdminTranslation",
     *  mappedBy="object",
     *  cascade={"persist", "remove"}
     * )
     * @Assert\Valid(deep = true)
     */
    private $translations;

    public function __construct()
    {
        $this->translations = new ArrayCollection();
    }
          
    /**
     * Set translations
     *
     * @param ArrayCollection $translations
     * @return Admin
     */
    public function setTranslations($translations)
    {
        foreach ($translations as $translation) {
            $translation->setObject($this);
        }

        $this->translations = $translations;
        return $this;
    }
    
     /**
     * Get translations
     *
     * @return ArrayCollection
     */
    public function getTranslations()
    {
        return $this->translations;
    }  

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set fonction
     *
     * @param string $fonction
     * @return Admin
     */
    public function setFonction($fonction)
    {
        $this->fonction = $fonction;

        return $this;
    }

    /**
     * Get fonction
     *
     * @return string 
     */
    public function getFonction()
    {
        return $this->fonction;
    }
    
    public function _toString(){
        
        return $this->prenom.' '.$this->nom;
        
    }
          
}
```

Here is the class AdminTranslation :

```
namespace Ip\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation;

/**
 * Entity\AdminTranslation.php

 * @ORM\Entity
 * @ORM\Table(name="admin_translations",
 *   uniqueConstraints={@ORM\UniqueConstraint(name="lookup_unique_idx", columns={
 *     "locale", "object_id", "field"
 *   })}
 * )
 */
class AdminTranslation extends AbstractPersonalTranslation
{
    /**
     * @ORM\ManyToOne(targetEntity="Ip\AdminBundle\Entity\Admin", inversedBy="translations")
     * @ORM\JoinColumn(name="object_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $object;    
}
```

And the Admin-generator.yml : 

```
generator: admingenerator.generator.doctrine
params:
    model: Ip\AdminBundle\Entity\Admin
    namespace_prefix: Ip
    concurrency_lock: ~
    bundle_name: AdminBundle
    pk_requirement: ~
    fields:  
      translations:
        formType: a2lix_translations
        label: Fonction 
        addFormOptions:
         locales: [fr, en]
         required: false
         fields: 
           fonction:
             locale_options:
               en:
                 label : Function    
               fr:
                 label : Fonction                     

    object_actions:
        delete: ~
    batch_actions:
        delete: ~
        
stylesheets:
   - bundles/a2lixtranslationform/css/a2lix_translation.css
javascripts:
   - /bundles/a2lixtranslationform/js/a2lix_translation.js   
   
builders:
    list:
        params:
            title: List for AdminBundle
            display: [id, fonction]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    new:
        params:
            title: New object for AdminBundle
            display: [id, fonction, translations]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Admin.fonction}|"
            display: [id, fonction, translations]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Admin.fonction}|"
            display: [id, fonction, translations]
            actions:
                list: ~
                new: ~
              
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
                
    filters:
        params:
            display: [id, username, email, password]
  ```

If someone could help me...

thanks a lot !
