### ISSUE TITLE
Cannot get extensions working with YAML

### ISSUE THREAD

**Issue by hoffmanns** [Atlantic18/DoctrineExtensions#1398]
I have set up everything like in the example without a framework. 

The extensions are working if I am using annotations, but if I include the YAMLDriver in configuration, the gedmo YAML fields are ignored.

Example:
```yaml
Models\AdmissionForm:
  type: entity
  table: admission_forms
  gedmo:
  translation:
    locale: locale
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      gedmo:
        - translatable
    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
```

Entity manager configuration:

```php
...
// globally used cache driver, in production use APC or memcached
$cache = new Doctrine\Common\Cache\ArrayCache;

$cachedAnnotationReader = new Doctrine\Common\Annotations\CachedReader(
    new Doctrine\Common\Annotations\AnnotationReader, // use reader
    $cache // and a cache driver
);
// create a driver chain for metadata reading
 $driverChain = new Doctrine\ORM\Mapping\Driver\DriverChain();



// // now we want to register our application entities,
// // for that we need another metadata driver used for Entity namespace
$annotationDriver = new Doctrine\ORM\Mapping\Driver\AnnotationDriver(
    $cachedAnnotationReader, // our cached annotation reader
    /* ... */ // paths to look in
);

$doctrineYAMLDriver = new Doctrine\ORM\Mapping\Driver\YamlDriver(/*...*/);

$driverChain->addDriver($annotationDriver, 'Models');
$driverChain->addDriver($doctrineYAMLDriver, 'Models');

Gedmo\DoctrineExtensions::registerMappingIntoDriverChainORM(
    $driverChain, // our metadata driver chain, to hook into
    $cachedAnnotationReader // our cached annotation reader
);

// general ORM configuration
$config = new Doctrine\ORM\Configuration;
/* ... */
// register metadata driver
$config->setMetadataDriverImpl($driverChain);

```

later:
```php
// translatable
$translatableListener = new Gedmo\Translatable\TranslatableListener;
$translatableListener->setTranslatableLocale('de');
$translatableListener->setDefaultLocale('de');
$translatableListener->setAnnotationReader($cachedAnnotationReader);
$evm->addEventSubscriber($translatableListener);

// timestampable
$timestampableListener = new Gedmo\Timestampable\TimestampableListener();
$timestampableListener->setAnnotationReader($cachedAnnotationReader);
$evm->addEventSubscriber($timestampableListener);
```

If I remove YAML driver and use annotations, everything works as expected, but if I add YAML driver or replace annotation driver, the translateable and timestampable functionality is not working when trying with specified YAML. 

E.g. when adding a translation: `Uncaught exception 'ReflectionException' with message 'Property locale does not exist' in /Users/stephanwork/repositories/enterprise_mercury/vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/TranslatableListener.php:307`

Any ideas to setup the extensions without a framework and use YAML mappings?

**Comment by l3pp4rd** [comment]
hi, there is an [example](https://github.com/Atlantic18/DoctrineExtensions/blob/master/example/em.php) for general setup with annotations. Concerning **YML**, you need to specify full path in driver to your mapping files `$xmlDriver = new YamlDriver(__DIR__.'/Mapping/Yaml');` for example, also adjust the extension.

You could also try switching the driver chain drivers, as that may impact priority:
``` php 
$driverChain->addDriver($doctrineYAMLDriver, 'Models');
$driverChain->addDriver($annotationDriver, 'Models');
```

**Comment by hoffmanns** [comment]
Hi, 
thank you for the quick reply. 

I am aware of the example, I have configured the Entity Manager according to the example and the extension is working with general setup using annotations in model classes.

The YAML driver is working if I remove the annotation driver completely, but it just seems to ignore any gedmo extension references like this:

```
  created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
```

Also, if I only use YAML driver and execute CLI 

` php vendor/bin/doctrine orm:generate:entities . --generate-annotations=true`

The generated model class lacks any gedmo extension annotations:

```
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;
```

Switching the driver chain also had no effect.
