### ISSUE TITLE
[Loggable] Double logging on an entity which extends an abstract entity.

### ISSUE THREAD

**Issue by diggersworld** [Atlantic18/DoctrineExtensions#1410]
In my project I have developed an `AbstractEntity` to save having to rewrite the same functionality many times. The class contains `status` (published, draft, unpublished) and `privacy` (private, public) options.

I then have my main entities extend this class, i.e. `Product`.

The problem I have is that I want to log when the `status` and `privacy` are changed, as well as attributes on the `Product` entity. It appears that because I've added the versioned annotation to attributes in both classes that two entries are added into the db.

AbstractEntity.php
```
/**
 * @ORM\HasLifecycleCallbacks()
 */
abstract class AbstractEntity
{
    /**
     * @ORM\Column(type="string")
     * @Gedmo\Versioned
     */
    protected $status;
    
    /**
     * @ORM\Column(type="string")
     * @Gedmo\Versioned
     */
    protected $privacy;
```
Product.php
```
/**
 * @ORM\Entity
 * @ORM\Table(name="product")
 * @ORM\HasLifecycleCallbacks()
 * @Gedmo\Loggable(logEntryClass="\Noisegate\CmsBundle\Entity\Log\ProductLog")
 */
class Product extends AbstractEntity
{
    /**
     * @ORM\Column(type="string")
     * @Gedmo\Versioned
     */
    protected $name;
    
    /**
     * @ORM\Column(type="string")
     * @Gedmo\Versioned
     */
    protected $slug;
```
ProductLog.php
```
/**
 * @ORM\Entity(repositoryClass="Gedmo\Loggable\Entity\Repository\LogEntryRepository", readOnly=true)
 * @ORM\Table(
 *      name="log_product",
 *      indexes={
 *          @ORM\Index(name="log_class_lookup_idx", columns={"object_class"}),
 *          @ORM\Index(name="log_date_lookup_idx", columns={"logged_at"}),
 *          @ORM\Index(name="log_user_lookup_idx", columns={"username"}),
 *      }
 * )
 */
class ProductLog extends AbstractLogEntry
{

}
```

Is there a correct way to use loggable when extending classes?

**Comment by l3pp4rd** [comment]
the result is same if you add [MappedSuperclass](http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html) annotation? but if it allows abstract classes probably it needs to be fixed.

**Comment by diggersworld** [comment]
I tried adding `@MappedSuperclass` to my `AbstractEntity` class however the issue still occurs.

```
namespace MyApp\CmsBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\HasLifecycleCallbacks()
 * @ORM\MappedSuperclass
 */
abstract class AbstractEntity
{
```

**Comment by diggersworld** [comment]
It appears I had configuration conflict:

```
gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```
and
```
stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            loggable: true
```
I have removed the Gedmo config and it's working as expected now.
