### ISSUE TITLE
The slughandler is not used with tree concept

### ISSUE THREAD

**Issue by Philalawst** [Atlantic18/DoctrineExtensions#1438]
Hello,

I try to use the SlugHandler concept but my setting is not used.

In my app/config.yml
```
 doctrine:
    ...
    orm:
        ...
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    tree:
                      type: annotation
                      alias: Gedmo
                      prefix: Gedmo\Tree\Entity
                      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
```

here my entity : 
```
<?php
namespace Mie\CmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\EventArgs;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks()
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="node_data_type", type="string")
 * @ORM\Table(name="node")
 * @ORM\Entity(repositoryClass="Mie\CmsBundle\Repository\NodeRepository")
 * @Gedmo\Tree(type="nested")
 */
class Node {
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="datetime", name="created_at")
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", name="updated_at")
     * @var \DateTime
     */
    private $updatedAt;
    
    /**
     * @ORM\Column(type="string", length=100)
     */
    protected $title;
    
    /**
     * @Gedmo\Slug(fields={"title"}, handlers={
     *    @Gedmo\SlugHandler(class="Gedmo\Sluggable\Handler\TreeSlugHandler", options={
     *        @Gedmo\SlugHandlerOption(name="parentRelationField", value="parent"),
     *        @Gedmo\SlugHandlerOption(name="separator", value="/")
     *   })
     * }, separator="-", updatable=true)
     * @ORM\Column(type="string", length=255)
     */
    protected $slug;
    
    
    /**
     * @ORM\Column(name="lft", type="integer")
     * @Gedmo\TreeLeft
     */
    private $lft;

    /**
     * @ORM\Column(name="rgt", type="integer")
     * @Gedmo\TreeRight
     */
    private $rgt;
    
    /**
     * @Gedmo\TreeLevel
     * @ORM\Column(name="lvl", type="integer")
     */
    private $lvl;

    /**
     * @ORM\Column(name="root", type="integer", nullable=true)
     * @Gedmo\TreeRoot
     */
    private $root;
    
    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Mie\CmsBundle\Entity\Node", inversedBy="children", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $parent;
    
    /**
     * @ORM\OneToMany(targetEntity="Mie\CmsBundle\Entity\Node", mappedBy="parent", orphanRemoval=true)
     * @var ArrayCollection
     */
    private $children;
    

    /**
     * Constructor
     */
    public function __construct() {
        $this -> children = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist() {
        $this -> setUpdatedAt(new \DateTime("now"));
        $this -> setCreatedAt(new \DateTime("now"));
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate() {
        $this -> setUpdatedAt(new \DateTime("now"));
    }

}

```

My test 
```
$nodePage = new Node();    
$nodePage->setTitle('test1');    
$manager->persist($nodePage);

$nodePage2 = new Node();    
$nodePage2->setTitle('test2');  
$nodePage2->setParent($nodePage);    
$manager->persist($nodePage2);
```

***field lft, rgt, root, lvl are correctly filled but slug field is empty***
It seems the SlugHandler is not used.
I don't see in the documentation a config to add to use this.

thanks,
Phil

**Comment by l3pp4rd** [comment]
it seems odd that your class is abstract, though. is the sluggable listener connected to event manager? check if it reads metadata from your node class

**Comment by Philalawst** [comment]
sorry! for my test, i remove the "abstract"

**Comment by Philalawst** [comment]
ok, I put this lines in my services.yml
```
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
```

It's works! 
Thanks
Phil
