### ISSUE TITLE
[SoftDeleteable] Deleted entities showing up on eager fetches

### ISSUE THREAD

**Issue by sonu27** [Atlantic18/DoctrineExtensions#1463]
Using v2.4.7 and Symfony 2.7.7 (also tested on Symfony 2.7.6), if I use `fetch="EAGER"` on one-to-many relations the "deleted" entities appear in the results.

E.g.
`<one-to-many field="items" target-entity="BasketItem" mapped-by="basket" fetch="EAGER">
      <cascade>
        <cascade-all/>
      </cascade>
    </one-to-many>`

Is this desired behaviour? Could I be doing something wrong?

```
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection:    default
                mappings:
                    AppBundle: ~
                result_cache_driver:
                    type: redis
                    host: "%redis_host%"
                    instance_class: Redis
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
```
