### ISSUE TITLE
[Translatable] Get translation fallback on every locales.

### ISSUE THREAD

**Issue by aurelienCastel** [Atlantic18/DoctrineExtensions#1662]
I am currently internationalizing an app, my fields are translatable but they don't have any translations yet.
I don't want to display blank fields, so if the field doesn't have a translation in the current locale yet, I want the default value to be displayed.
At the moment I can get this behaviour but only if the current locale is the default locale, I want this to happend no matter what the current locale is.

**Entity:**

```
/**
 * @ORM\Entity
 * @ORM\Table(name="dropcause")
 */
class DropCause implements Translatable
{
    /**
     * @Gedmo\Translatable
     * @ORM\Column(type="string",length=255)
     */
    protected $name;
    // I want this value to be displayed in the view
    // if there is no translation avaible for the current locale.

    /**
     * @Gedmo\Locale
     */
    private $locale;

    // [...]

    public function setTranslatableLocale($locale)
    {
        $this->locale = $locale;
    }
```

**config.yml:**

```
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            translatable: true

stof_doctrine_extensions:
    gedmo:
        translatable:
            translatable_listener:
                set_translation_fallback: true
```

**Comment by l3pp4rd** [comment]
Hi, you have to [set the default locale](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/Translatable/TranslatableListener.php#L295) to whatever you want to fallback to.

**Comment by aurelienCastel** [comment]
Okay, basically my ``.yaml`` was wrong.

I had to change this:

```
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            translatable: true

stof_doctrine_extensions:
    gedmo:
        translatable:
            translatable_listener:
                set_translation_fallback: true
```

To this:

```
stof_doctrine_extensions:
    default_locale: "%locale%"
    translation_fallback: true
    orm:
        default:
            translatable: true
```

**Comment by lukepass** [comment]
This isn't working for me. I have this configuration:

```
# Doctrine Extensions Configuration
stof_doctrine_extensions:
    default_locale: 'en'
    translation_fallback: true
    persist_default_translation: true
    orm:
        default:
            timestampable: true
            blameable: true
            translatable: true
```

When I retrieve a translation without a value it doesn't have the default content but it's empty.
