### ISSUE TITLE
Why loggable is inserting two rows?

### ISSUE THREAD

**Issue by roberto910907** [Atlantic18/DoctrineExtensions#1785]
Sorry for my english but I can't found any solution for this issue.

I notice with debugging with XDebug when i want to persist the entity the **flush** method is called twice in **Gedmo/Loggable/LoggableListener.php:187** the second time loggable persists a second row but the only difference is that the username is null, but fields action, loggued_at, object_id, object_class, version and data has exactly the same information than the first row.

How could I solve that?

Thanks in advance.

**Comment by l3pp4rd** [comment]
Hi, it seems like you have 2 loggable listeners subscribed into ORM. check your code in order to be sure there is only one listener.

**Comment by roberto910907** [comment]
Thanks, you're right. The error was that i had configured:

services.yml
    ```
gedmo.listener.loggable:
        class: Gedmo\Loggable\LoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```
And also:

config.yml under orm
```
mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
```

It seems to be duplicated, so I removed the service declaration and it's working now.

Thank you so much.
