### ISSUE TITLE
[Blameable] Integer is not a valid Doctrine type mapping

### ISSUE THREAD

**Issue by tezvi** [Atlantic18/DoctrineExtensions#2006]
https://github.com/Atlantic18/DoctrineExtensions/blob/ee6e427c759da76b65597870e2bae36fc7b09631/lib/Gedmo/Blameable/Mapping/Driver/Annotation.php#L29-L33

Is **int** value a valid Doctrine mapping type? It seems that "**integer**" should be used instead.
I've managed to defined custom doctrine type in symfony configuration so this works for me at framework level:

```
doctrine:
    dbal:
        types:
            int: Doctrine\DBAL\Types\IntegerType
```

However, it would be nice to have "integer" value in $validTypes collection as well, so everyone can be happy :)

Something similar is reported here but closed without proper resolution https://github.com/Atlantic18/DoctrineExtensions/issues/1137
