### ISSUE TITLE
ORM Sluggable + SoftDeleteable

### ISSUE THREAD

**Issue by GSwidnicki** [Atlantic18/DoctrineExtensions#2094]
I have Entity that uses Sluggable and SoftDeleteable. 
I add row with title `foo` and Sluggable generate slug `foo`. 
I soft-delete this row. 
I still have row in database with slug `foo`.
When I want to add again row with title `foo` Sluggable should generate slug `foo-1` because in database already exists row (this deleted) with slug `foo`, but generate `foo` and I have an exception because slug is not unique...

**Comment by AkenRoberts** [comment]
You can disable the soft delete checks when generating slugs by:

```php
$sluggableListener->addManagedFilter(SoftDeleteableFilter::class);
```

This will disable the soft delete query filter when looking up existing slugs. There's some more info in #449 (along with alternative methods for one-off scenarios). Sylius also [has an example](https://github.com/Sylius/Sylius/pull/1002) of calling it globally.

There may be a way to do it with a services entry in Symfony's config, I just don't know what that would look like off the top of my head.

**Comment by sabat24** [comment]
> When I want to add again row with title foo Sluggable should generate slug foo-1

Sluggable behaviour is right. It should generate slug `foo` as there is no another such slug. It doesn't matter that it exists in DB. You deleted it. To solve the problem of uniqueness you should create unique constrant on both fields instead of one

`ADD CONSTRAINT UNIQUE (slug, deleted_at)`

in Symfony using annotations

```php
/**
 * @ORM\Table(uniqueConstraints={@UniqueConstraint(name="field_slug_deleted", columns={"slug","deleted_at"})})
 */
```

**Comment by AkenRoberts** [comment]
Hopefully these ideas have helped solve your situation. 🤞

**Comment by GSwidnicki** [comment]
I solved this problem like this (Symfony 5.2.3 => services.yaml):
```
services:
    Gedmo\Sluggable\SluggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ addManagedFilter, [ "soft_deleteable" ] ]
```

**Comment by mcebular** [comment]
Slight amendment of above solution with servicey.yaml that worked for me for Symfony 6.3:

```yml
services:
  gedmo.listener.sluggable:
    class: Gedmo\Sluggable\SluggableListener
    tags:
      - { name: doctrine.event_listener, event: 'prePersist' }
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]
      - [ addManagedFilter, [ "softdeleteable" ] ]
```

Actual source for above listener service config is in https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/symfony.md#doctrine-extension-listener-services (except for the `addManagedFilter` line).

Note: filter name is defined in `doctrine.yaml`, under `doctrine.orm.filters.<filter_name>` (in case you are unsure if you named it `soft_deleteable`, `softdeleteable`, or something else.
