### ISSUE TITLE
custom LoggableListener inject service

### ISSUE THREAD

**Issue by Tanktiger** [Atlantic18/DoctrineExtensions#2101]
Hi,
i'm doing an upgrade from symfony 3.4 to 4.4. 

Installed doctrine-extensions: 2.4.39
Installed doctrine/dbal: 2.10.1
Installed doctrine/orm: 2.7.1
Installed symfony: 4.4.5

I've installed an encryption bundle michaeldegroot/doctrine-encrypt-bundle in version 4.0.3. I have multiple entities with encrypted and versioned fields. I want to save the encrypted value in the ext_log_entries table. Before the upgrade everything worked fine with my custom LoggableListener. After the upgrade i'm getting the following error:

> Call to a member function encrypt() on null in CustomLoggableListener.php (line 141)

This is my config before the upgrade:
```
gedmo.listener.loggable:
        class: foobar\CoreBundle\Listener\CustomLoggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setEncryptor, [ "@ambta_doctrine_encrypt.encryptor" ] ]
```

This is my config after the upgrade:
```
App\foobar\CoreBundle\Listener\CustomLoggableListener:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            - [ setEncryptor, [ '@ambta_doctrine_encrypt.encryptor' ] ]
```

And this is my CustomLoggableListener:

```php
namespace App\foobar\CoreBundle\Listener;

use Ambta\DoctrineEncryptBundle\Configuration\Encrypted;
use Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface;
use Doctrine\Common\Annotations\AnnotationReader;
use Doctrine\Common\Persistence\ObjectManager;
use Gedmo\Loggable\Mapping\Event\LoggableAdapter;
use Gedmo\Tool\Wrapper\AbstractWrapper;
use Gedmo\Loggable\LoggableListener as GedmoLoggableListener;

class CustomLoggableListener extends GedmoLoggableListener
{
    /**
     * @var EncryptorInterface
     */
    private $encryptor;

    /**
     * @param EncryptorInterface $encryptor
     * @required
     */
    public function setEncryptor(EncryptorInterface $encryptor)
    {
        dump($encryptor);
        $this->encryptor = $encryptor;
    }

    /**
     * @return EncryptorInterface
     */
    public function getEncryptor()
    {
        return $this->encryptor;
    }
    /**
     * Handle any custom LogEntry functionality that needs to be performed
     * before persisting it
     *
     * @param object $logEntry The LogEntry being persisted
     * @param object $object   The object being Logged
     */
    protected function prePersistLogEntry($logEntry, $object)
    {
    }

    /**
     * Returns an objects changeset data
     *
     * @param LoggableAdapter $ea
     * @param object $object
     * @param object $logEntry
     *
     * @return array
     */
    protected function getObjectChangeSetData($ea, $object, $logEntry)
    {
        $om = $ea->getObjectManager();
        $wrapped = AbstractWrapper::wrap($object, $om);
        $meta = $wrapped->getMetadata();
        $config = $this->getConfiguration($om, $meta->name);
        $uow = $om->getUnitOfWork();
        $encryptedFields = $this->getEncryptedFields($meta->name, $object, $om);
        $newValues = array();

        foreach ($ea->getObjectChangeSet($uow, $object) as $field => $changes) {
            if (empty($config['versioned']) || !in_array($field, $config['versioned'])) {
                continue;
            }
            if ($changes[0] === $changes[1]) continue;

            //special handling for boolean fields
            if (is_bool($changes[0]) && $changes[0] === boolval($changes[1])) continue;

            $value = $changes[1];

            if (isset($encryptedFields[$field]) && $encryptedFields[$field] === $changes[0]) {
                //same values - no need to save to log
                continue;
            } elseif (isset($encryptedFields[$field])) {
                //it is an encrypted field - so we need to save an encrypted value in the log table
                $value = $this->getEncryptor()->encrypt($changes[1]);
            }


            if ($meta->isSingleValuedAssociation($field) && $value) {
                if ($wrapped->isEmbeddedAssociation($field)) {
                    $value = $this->getObjectChangeSetData($ea, $value, $logEntry);
                } else {
                    $oid          = spl_object_hash($value);
                    $wrappedAssoc = AbstractWrapper::wrap($value, $om);
                    $value        = $wrappedAssoc->getIdentifier(false);
                    if (!is_array($value) && !$value) {
                        $this->pendingRelatedObjects[$oid][] = array(
                            'log'   => $logEntry,
                            'field' => $field,
                        );
                    }
                }
            }
            $newValues[$field] = $value;
        }

        return $newValues;
    }

    /**
     * @param $entity
     * @param ObjectManager $om
     * @return array
     */
    protected function getEncryptedFields($class, $entity, $om)
    {
        try {
            $cols = $om->getClassMetadata($class)->fieldMappings;
            $reflectionClass = new \ReflectionClass($class);
            $reader = new AnnotationReader();

            $encryptedFields = array();
            foreach($cols as $fieldname => $col){
                try {
                    $getter = 'get'.ucfirst($fieldname);
                    if (method_exists($entity, $getter)) {
                        $value = $entity->$getter();
                        $property = $reflectionClass->getProperty($fieldname);


                        $annotation = $reader->getPropertyAnnotation(
                            $property,
                            Encrypted::class
                        );
                        if ($annotation) {
                            $encryptedFields[$fieldname] = $this->getEncryptor()->encrypt($value);
                        }
                    }
                } catch ( \Exception $e) {
                    //do nothing
                }
            }

            return $encryptedFields;
        } catch(\Exception $e) {
            return [];
        }
    }
}
```

The error is thrown when i want to call the ->encrypt() function. I've inserted a dump in the setEncryptor function. The dump is successfully called but when the subscriber is called by the event, the setEncryptor function is not called anymore.

Here is the stack trace:

```
Error:
Call to a member function encrypt() on null

  at C:\projects\api_upgrade_test\src\foobar\CoreBundle\Listener\CustomLoggableListener.php:141
  at App\foobar\CoreBundle\Listener\CustomLoggableListener->getEncryptedFields('App\\foobar\\CoreBundle\\Entity\\Legalcase', object(Legalcase), object(EntityManager))
     (C:\projects\api_upgrade_test\src\foobar\CoreBundle\Listener\CustomLoggableListener.php:71)
  at App\foobar\CoreBundle\Listener\CustomLoggableListener->getObjectChangeSetData(object(ORM), object(Legalcase), object(LogEntry))
     (C:\projects\api_upgrade_test\vendor\gedmo\doctrine-extensions\lib\Gedmo\Loggable\LoggableListener.php:296)
  at Gedmo\Loggable\LoggableListener->createLogEntry('update', object(Legalcase), object(ORM))
     (C:\projects\api_upgrade_test\vendor\gedmo\doctrine-extensions\lib\Gedmo\Loggable\LoggableListener.php:197)
  at Gedmo\Loggable\LoggableListener->onFlush(object(OnFlushEventArgs))
     (C:\projects\api_upgrade_test\vendor\symfony\doctrine-bridge\ContainerAwareEventManager.php:58)
  at Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent('onFlush', object(OnFlushEventArgs))
     (C:\projects\api_upgrade_test\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:3405)
  at Doctrine\ORM\UnitOfWork->dispatchOnFlushEvent()
     (C:\projects\api_upgrade_test\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php:373)
  at Doctrine\ORM\UnitOfWork->commit(null)
     (C:\projects\api_upgrade_test\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:368)
  at Doctrine\ORM\EntityManager->flush()
     (C:\projects\api_upgrade_test\src\foobar\CoreBundle\Controller\LegalcaseController.php:372)
  at App\foobar\CoreBundle\Controller\LegalcaseController->editAction(object(Request), object(Legalcase), object(ServiceActivityService), object(LegalcaseHistoryLogger), object(LegalcaseRankingService), object(Flasher), object(Logger), object(TraceableEventDispatcher))
     (C:\projects\api_upgrade_test\vendor\symfony\http-kernel\HttpKernel.php:146)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (C:\projects\api_upgrade_test\vendor\symfony\http-kernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (C:\projects\api_upgrade_test\vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (C:\projects\api_upgrade_test\public\index.php:25)                
```

Could someone help me to find a solution?

**Comment by AkenRoberts** [comment]
How are you configuring Doctrine Extensions in Symfony? Are you using a bundle or doing it manually?

**Comment by Tanktiger** [comment]
@AkenRoberts i'm using the stof/doctrine-extensions-bundle and the gedmo/doctrine-extensions. The services are configured in the services.yaml.

I've fixed it. It was a double configured listener. My CustomLoggableListener was called twice and in the first run the encryptor was not defined. The Problem was, i've not override the loggable service from stof in the services.yaml

```
#override stofs definition of loggable to prevent double execution
stof_doctrine_extensions.listener.loggable: '@App\foobar\CoreBundle\Listener\CustomLoggableListener'
```

this is my stof_doctrine_extensions.yaml
```
stof_doctrine_extensions:
    default_locale: '%env(LOCALE)%'
    orm:
        default:
            timestampable: true
            loggable: true
            translatable: true
            softdeleteable: true
    #override listeners
    class:
        loggable:       App\foobar\CoreBundle\Listener\CustomLoggableListener
```

and now i'm setting the encryptor with property injection instead of setter injection
```
App\foobar\CoreBundle\Listener\CustomLoggableListener:
        public: true
        properties:
            encryptor: '@ambta_doctrine_encrypt.encryptor'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
```

Now my Listener is only called once with the encryptor.
