### ISSUE TITLE
Specified non-existing directory in doctrine.yaml

### ISSUE THREAD

**Issue by lebadapetru** [Atlantic18/DoctrineExtensions#2160]
Hey guys,

I'm using `"gedmo/doctrine-extensions": "^2.4",` with symfony 5.1 in a new project and while reading [your docs](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/symfony4.md) i came across this bug:

` Specified non-existing directory "/var/www/app%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Timestampable" as Doc
  trine mapping source.`

My doctrine.yaml config looks like this:

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        schema_filter: ~^(?!.*[_]join$).*$~
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Timestampable:
                is_bundle: false
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Timestampable\Entity
                dir: "%kernel.project_dir%%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Timestampable/Entity"

```

I'm also aware of [this package](https://github.com/stof/StofDoctrineExtensionsBundle) and i'm not quite sure what's the relation between gedmo and stof... i've seen topics regarding stof on gedmo and vice versa, is one of the package forked from the other or?

I'm not sure how this is suppose to work, as far as i know this package is quite old and has been through some changes and maybe the reason why i couldn't find any info regarding this issue is because the older users might know some workarounds but for newer ones is really hard to implement this. Can anyone help me out please?
