### ISSUE TITLE
Type error as of #2153

### ISSUE THREAD

**Issue by FireLizard** [Atlantic18/DoctrineExtensions#2167]
In cause of #2153 when return type of a translated field's getter-method is e.g. **string** it throws the following exception:
```
Type error: Return value of My\Entity\Taxon::getTitle() must be of the type string, null returned
```
My Doctrine Entity
```php
<?php
namespace My\Entity;

class Taxon
{
    /**
     * @var string
     */
    protected $title = '';

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }
```

```yaml
My\Entity\Taxon:
    type: entity

    gedmo:
        translation:
            locale: locale
            # using specific personal translation class
            entity: My\Entity\Translation\Taxon

    fields:
        title:
            type: string
            length: 255
            gedmo:
                translatable:
                    fallback: true

    oneToMany:
        translations:
            targetEntity: My\Entity\Translation\Taxon
            mappedBy: object
            cascade: ["persist", "remove"]

```
My environment:
```bash
$ php -v
PHP 7.0.27 (cli) (built: Feb 17 2018 02:11:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```
```bash
$ composer show -l gedmo/*
gedmo/doctrine-extensions v2.4.42 v2.4.42 Doctrine2 behavioral extensions
```
```bash
$ composer show -l doctrine/*
doctrine/annotations                v1.4.0  v1.4.0  Docblock Annotations Parser
doctrine/cache                      v1.6.2  v1.6.2  Caching library offering an object-oriented API for many cache back...
doctrine/collections                v1.4.0  v1.4.0  Collections Abstraction library
doctrine/common                     v2.7.3  v2.7.3  Common Library for Doctrine projects
doctrine/data-fixtures              v1.2.2  v1.2.2  Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.5.13 v2.5.13 Database Abstraction Layer
doctrine/doctrine-bundle            1.10.3  1.10.3  Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5   1.3.5   Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   v2.4.1  3.0.4   Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.3.2  v1.3.2  Symfony DoctrineMigrationsBundle
doctrine/inflector                  v1.2.0  v1.2.0  Common String Manipulations with regard to casing and singular/plur...
doctrine/instantiator               1.0.5   1.0.5   A small, lightweight utility to instantiate objects in PHP without ...
doctrine/lexer                      1.0.2   1.0.2   PHP Doctrine Lexer parser library that can be used in Top-Down, Rec...
doctrine/migrations                 v1.5.0  v1.5.0  Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.5.14 v2.5.14 Object-Relational-Mapper for PHP
```
