### ISSUE TITLE
[References] Adding the ReferencesListener breaks all other Doctrine extensions.

### ISSUE THREAD

**Issue by borovan** [Atlantic18/DoctrineExtensions#821]
Hi - so I've been using Tree, Blameable and Timestampable with no problems at all.  I've recently had a need for the ORM/ODM cross-relational functionality, so added in the ReferencesListener, and although it works fine none of the other extensions work at the same time.

Blame and Timestamp both just insert null values now, and Tree gives me the error "Tree listener was not found on your entity manager, it must be hooked into the event manager".

I've done a var_dump in the Gedmo\Tree\Entity\Repository\AbstractTreeRepository code and it seems that whenever this line (from my services.yml) is called

```
        - [ registerManager, [ 'entity', "@doctrine.orm.entity_manager" ] ]
```

then $em->getListeners() returns an empty array.  No exceptions are thrown, just the other extensions fail to work.  If I comment out that one line, the situation is reversed (Everything works apart from references).

I've tried with and without Stof, nothing changes.  I've tried injecting the entity managers in the constructor, that doesn't work either.  I've also tried with just one listener where I pass in 2 entity managers.  I've included the relevant bit of services.yml below.

Thanks,
Adam

```
# Gedmo
gedmo.listener.reference.mysql:
    class: Gedmo\References\ReferencesListener
    tags:
        - { name: doctrine.event_subscriber, connection: game }
    calls:
        - [ setAnnotationReader, [ "@annotation_reader" ] ]
        - [ registerManager, [ 'document', "@doctrine_mongodb.odm.document_manager" ] ]

gedmo.listener.reference.mongodb:
     class: Gedmo\References\ReferencesListener
     tags:
        - { name: doctrine_mongodb.odm.event_subscriber }
     calls:
       - [ setAnnotationReader, [ "@annotation_reader" ] ]
        - [ registerManager, [ 'entity', "@doctrine.orm.entity_manager" ] ]

gedmo.listener.tree:
    class: Gedmo\Tree\TreeListener
    tags:
        - { name: doctrine.event_subscriber, connection: game }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.timestampable:
    class: Gedmo\Timestampable\TimestampableListener
    tags:
        - { name: doctrine.event_subscriber, connection: game }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]

gedmo.listener.blameable:
    class: Gedmo\Blameable\BlameableListener
    tags:
        - { name: doctrine.event_subscriber, connection: game }
    calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
```
