### ISSUE TITLE
[wip-v2.4.0] Doctrine ObjectHydrator error on postLoad

### ISSUE THREAD

**Issue by soullivaneuh** [Atlantic18/DoctrineExtensions#988]
I use DoctrineExtensions wip-v2.4.0 with this following bundles:

``` json
"sonata-project/admin-bundle": "2.2.*",
"sonata-project/doctrine-orm-admin-bundle": "2.2.*",
"gedmo/doctrine-extensions": "dev-wip-v2.4.0",
"a2lix/translation-form-bundle": "2.*",
```

I set up translation in one entity `Customer` and use a2lix form in sonata admin to edit them, works fine.

But, when I want to list my customers in sonata, I have this following error:

```
ContextErrorException: Notice: Trying to get property of non-object in /home/sullivan/projects/nexylan/nexylan-com/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php line 480
```

After investigations, I found that the issue is committed [here](https://github.com/l3pp4rd/DoctrineExtensions/blob/wip-v2.4.0/lib/Gedmo/Translatable/TranslatableListener.php#L345).

To "fix" it, I set the skipOnLoad to true, like this:

``` yml
    gedmo.listener.translatable:
        class: Gedmo\Translatable\TranslatableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setSkipOnLoad, [ true ] ]
            - [ setAnnotationReader, [ @annotation_reader ] ]
            - [ setTranslatableLocale, [ %locale% ] ]
```

For now, it works but I don't know why is not working with the onload event and I don't know what is the consequences of disable it.

Thanks to anyone can help me.

PS: What is the difference between 2.4.0-wip and [3.0.0-wip](https://github.com/l3pp4rd/DoctrineExtensions/pull/764) ?
